- alias: "Rocket Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_number.rocket_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "rocket/led/set"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'